apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp3-redis-runtime
  labels:
    app: tp3-redis-runtime
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp3-redis-runtime
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: tp3-redis-runtime
    spec:
      containers:
      - name: tp3-redis-runtime
        image: quay.io/mmdutra14/mateusdutra-tp3-runtime:0.8.1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: functionzipfile
          mountPath: /app/functionzipfile64
          subPath: functionzipfile64
        env:
        - name: REDIS_HOST
          value: "192.168.121.171"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_INPUT_KEY
          value: "metrics"
        - name: REDIS_OUTPUT_KEY
          valueFrom:
            configMapKeyRef:
              name: outputkey
              key: REDIS_OUTPUT_KEY
        - name: SLEEP_TIME
          value: "5"
        - name: ROOT_FUNCTION_MODULE
          valueFrom:
            configMapKeyRef:
              name: outputkey
              key: ROOT_FUNCTION_MODULE
      restartPolicy: Always
      volumes:
      - name: functionzipfile
        configMap:
          name: functionzipfile

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp3-dashboard-streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp3-dashboard-streamlit
  template:
    metadata:
      labels:
        app: tp3-dashboard-streamlit
    spec:
      containers:
        - name: dashboard
          image: quay.io/mmdutra14/mateusdutra-tp3-dashboard:0.2
          ports:
            - containerPort: 8501
          env:
          - name: REDIS_HOST
            value: "192.168.121.171"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_INPUT_KEY
            value: "metrics"
          - name: REDIS_OUTPUT_KEY
            valueFrom:
              configMapKeyRef:
                name: outputkey
                key: REDIS_OUTPUT_KEY