apiVersion: v1
kind: Service
metadata:
  name: tp3-dashboard-service
spec:
  type: NodePort
  selector:
    app: tp3-dashboard-service
  ports:
    - port: 80
      targetPort: 8501
      nodePort: 30000
